### ISSUE TITLE
Metadata quality checks list and implementation tracking

### ISSUE THREAD

**Issue by MalditoBarbudo** [sapfluxnet/sapfluxnetQC1#2]
Here is a list of Metadata Quality Checks, indicating if their implementation is done yet or not. Please feel free to add checks in the comments and I will add them to the list.
# **Metadata Quality Checks**

(Checked boxes indicates implementation in sapfluxnetr R package)
- [x] **Coordinates**: Check if provided coordinates are correct and are inside site country.
    _Implemented, using the rgeos and sp packages_
- [x] **Unique Site & Country name**: Check if provided site and country combination is unique, in order
    to ensure adequate data flow in the scripts. _Implemented in the `df_received_to_accepted`
    function._
- [x] **Duplicate contributors**: Check if a contributor already exists, and if so, that the site is new, in 
     order to avoid duplicate entries.  _Not fix. It is no needed at the moment_
- [x] **Adequate range in numerical values**: Check if numerical metadata is in a reasonable
    biological/physiological/environmental/... range. _Implemented in `qc_out_of_range` function_
- [x] **Species names correctness**: Check if provided species names are spelled correctly and
    correspond to the right plant. _Implemented, using the tpl and tpldata packages_
- [x] **Concordance between `pl_species` and `sp_names` variables**: Check if species provided in
    both variables are the same. _Implemented in `qc_species_verification`_
- [x] **Number of trees**: Check if number of trees per species agrees with number of trees provided in
    the tree metadata.  _Implemented in `qc_species_verification`_
- [x] **Plant treatment**: Check if plant treatments, if any, are identical between trees (e.g. Drought and
     drought). _Implemented in `qc_pl_treatments`. At the moment only information about treatments
     is returned, as check and fix probably must be done at hand_
- [x] **Enviromental variables data presence**: Check if all environmental variables filled in the
    metadata really have associated data in the environmental data file. _Implemented in
    `qc_env_vars_presence`_.
- [x] **Timestamp format**: Check if the timestamp format is adequate, ~~and if not, fix it (if it is
    possible)~~. As errors are contributor dependent, automatic fixes are not possible. _Implemented
    in `qc_timestamp_errors` function, indicating the intervals where errors are found_
- [x] **Metadata columns**: Check that all the metadata variables are present and that their classes are
    correct
- [x] **Biomes**: Function to assign a biome to the site based on the coordinates (or
    Annual Mean Temperature and Annual Mean Precipitation).
## **Site_md specific checks**
- [x] **email**: Check if `si_contact_email` and `si_addcontr_email` are valid email directions. 
     *Implemented in `qc_email_check`
- [x] **Dictionaries for factors**: Check if factor variables (`si_country`, `si_dist_mgmt`, `si_igbp`)
    have valid values.
## **Stand_md specific checks**
- [x] **Dictionaries for factors**: Check if factor variables have valid values.
- [x] **Soil texture**. Implemented by Marie Sirot in `qc_soil_texture` function
## **Species_md specific checks**
- [x] **Dictionaries for factors**: Check if factor variables have valid values.
## **Plant_md specific checks**
- [x] **Dictionaries for factors**: Check if factor variables have valid values.
## **Environmental_md specific checks**
- [x] **Dictionaries for factors**: Check if factor variables have valid values.
- [x] **Conversion between radiation types**: Functions to convert between radiation types to
    standardize metadata. Implemented in `qc_rad_conversion` function (conversion between sw_in and ppfd_in)

**Comment by MalditoBarbudo** [comment]
All items have been implemented, closing the issue.
